#!/bin/bash
# Mock vnstat output
# Format compatible with: awk '{print $8" "substr ($9, 1, 3)}'
# We need $8 and $9 to be present.
# line: today rx tx total avg
# line: today 1 2 3 4 5 6 7 8 9
echo "       today      1.00 GiB      1.00 GiB      2.00 GiB"
